name: ZXP Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      # Decrypt encrypted file
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/567953453821/locations/global/workloadIdentityPools/github-action-pool/providers/github'
          service_account: 'github-action@nijikan.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Install SOPS
        run: |
          curl -L -O https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.exe
          mv sops-v3.8.1.exe sops.exe
      - name: Decrypt file
        shell: bash
        run: |
          ./sops.exe -d credential.enc.json > credential.json
        
      # Build ZXP
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --legacy-peer-deps
      - run: npm run zxp

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_NAME: ${{ steps.extract_names.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.extract_names.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.extract_names.outputs.SOURCE_TAG }}
        with:
          files: ./dist/zxp/net.ouvill.nijikan.zxp
