name: sample

on:
  #  手動実行
  workflow_dispatch:


jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        run: echo "Hello world!"
